export const BlogPosts = [
    {
        id: 1,
        title: '3-Slot Finality: The Next Evolution in Ethereum Consensus',
        description: "How a breakthrough in consensus design could reduce Ethereum's finality time from minutes to seconds",
        content: ``,
        author: 'Utsav Sharma',
        date: 'Aug 9, 2025',
        slug: '3-slot-finality',
        tags: ['Research'],
        link: 'https://0xsenpai.substack.com/p/3-slot-finality-the-next-evolution',
    },
    {
        id: 2,
        title: "Understanding Ethereum's RANDAO Mechanism",
        description: 'Exploring How Randomness Secures the Beacon Chain and the Ongoing Efforts to Strengthen It Against Manipulation',
        content: ``,
        author: 'Utsav Sharma',
        date: 'Apr 27, 2025',
        slug: 'randao-mechanism',
        tags: ['Research'],
        link: 'https://0xsenpai.substack.com/p/understanding-ethereums-randao-mechanism',
    },
    {
        id: 3,
        title: 'Hash-Based Signatures: A Quantum-Resistant Future?',
        description: 'Beyond RSA & ECDSA: The Future of Digital Signatures in a Post-Quantum World',
        content: ``,
        author: 'Utsav Sharma',
        date: 'Apr 1, 2025',
        slug: 'hash-based-signatures',
        tags: ['Research'],
        link: 'https://0xsenpai.substack.com/p/hash-based-signatures-a-quantum-resistant',
    },
    {
        id: 4,
        title: 'Elliptic Curve Digital Signature Algorithm (ECDSA)',
        description: 'One of the most significant aspects of bitcoin, or in general any cryptographic currency, is its use of digital signatures. In digital currency, ownership is established by a piece of digital data as opposed to...',
        content: ``,
        author: 'BlocSoc IITR',
        date: 'Apr 4, 2023',
        slug: 'ecdsa',
        tags: ['Research'],
        link: 'https://medium.com/@blocsoc.acm/ecdsa-26402064fd34',
    },
    {
        id: 5,
        title: 'Gas Optimization in Smart Contracts',
        description: 'As a blockchain scales , scarce resources may become too expensive resulting in only wealthier people being able to participate thereby reducing decentrality , and this in-turn will...',
        content: ``,
        author: 'BlocSoc IITR',
        date: 'Sep 8, 2022',
        slug: 'gas-optimization',
        tags: ['Research'],
        link: 'https://medium.com/@blocsoc.acm/gas-optimization-in-smart-contracts-d4bd508dd361',
    },
    {
        id: 6,
        title: 'Unfolding the Terra-Luna crash',
        description: "Terra is a proof-of-stake layer 1 blockchain built using the Cosmos SDK, propagating the idea of \"decentralized money\". According to Terra's white paper, the founders' goal was to...",
        content: ``,
        author: 'BlocSoc IITR',
        date: 'Jun 17, 2022',
        slug: 'terra-luna',
        tags: ['Research', 'News'],
        link: 'https://medium.com/@blocsoc.acm/unfolding-the-terra-luna-crash-b7e81beefab',
    }
]
